#!/bin/bash
echo "-------------------------------------"
echo "Your command:"
echo "-calc | -c -(sum,sum,mult,div)- -number1- -number2-";
echo "-search | -s -dirName- -regex-"
echo "-strlen | str -string-"
echo "-log | -l without params"
echo "-exit -e -code"
echo "-help | -h"
echo "-interactive | -i"
echo "Exit code:"
echo "1 - invalid number of arg"
echo "2 - parametr is not number"
echo "3 - file don't exist"
echo "4 - file can't be read"
echo "5 - file can't be write"
echo "6 - Division on zero"
echo "---------------------------------------"
